nelmio_api_doc:
    documentation:
        info:
            title: Syrniki
            description: Kyky epta
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/basket
            - ^/order
            - ^/promotion
